# Generated by Django 4.0.2 on 2022-07-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=101)),
                ('description', models.TextField(max_length=900, null=True)),
                ('email', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='re',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=101)),
                ('description', models.TextField(max_length=900, null=True)),
            ],
            options={
                'db_table': 'EventOrganizer_re',
            },
        ),
    ]
